### PR TITLE
Separate functionality into separate files

### LINKED ISSUE #32: Split up main.py into different files

### PR DESCRIPTION
**Pull request by L1Z3**
Closes #32.

### CODE REVIEW

**Comment by L1Z3** [comment]
> Should I close the pull for #31 and integrate it into this when it's merged?

Nope, it's fine! I'll merge yours to main first.

**Review by TheDoctorHD — DISMISSED** [review]
Looks good!

**Comment by TheDoctorHD** [comment]
(add commit to integrate the steam closing before merging, but everything so far looks great)

**Review by TheDoctorHD — APPROVED** [review]
Lgtm

**Pull request merged**
