### PR TITLE
Closing steam

### LINKED ISSUE #15: Ensure Steam is closed before adding shortcut

### PR DESCRIPTION
**Pull request by TheDoctorHD**
Closes #15

### CODE REVIEW

**Review by L1Z3 — CHANGES_REQUESTED** [review]
I feel like we should break this out into a separate function

**Comment by TheDoctorHD** [comment]
> I feel like we should break this out into a separate function

That's how I did it initially but I didn't think it would be used anywhere else. I'll make the changes real quick though.

**Comment by L1Z3** [comment]
i might use it somewhere else in a minute lol

**Comment by L1Z3** [comment]
wait can you also make it accept any program name

**Comment by TheDoctorHD** [comment]
> wait can you also make it accept any program name

Just saw this but already done lol

**Review by L1Z3 — DISMISSED** [review]

**Comment by L1Z3** [comment]
actually we should also probably not kill it, but just wait for it to close with a timeout

**Review by L1Z3 — APPROVED** [review]
@TheDoctorHD if you're okay with these changes, go ahead and merge

**Pull request merged**
