### PR TITLE
Option to Scan For or Download Cemu

### PR DESCRIPTION
**Pull request by TheDoctorHD**
Added in the option to scan for or download Cemu, which is asked in that order after EmuDeck is checked for and before the path is asked manually. Also changed wait_for_confirmation to output a boolean to make if statements simpler.

### CODE REVIEW

**Comment by L1Z3** [comment]
Nice! I pushed a commit cleaning up a couple of things--feel free to look it over and tell me if it looks good!

Other than that, I wonder if the scan for Cemu feature will actually work for anyone. Your code is fine, it's just that, scanning the filesystem can take a _long time_ and so it might just be better to not give the user that option. Let me know what you think though!

**Review by TheDoctorHD — COMMENTED** [review]
Looks good to me!

**Comment by TheDoctorHD** [comment]
> Nice! I pushed a commit cleaning up a couple of things--feel free to look it over and tell me if it looks good!
> 
> Other than that, I wonder if the scan for Cemu feature will actually work for anyone. Your code is fine, it's just that, scanning the filesystem can take a _long time_ and so it might just be better to not give the user that option. Let me know what you think though!

Your commit looks good. To answer your question on scanning, I tested the script on my own 1.84TB drive, of which my Users folder contains 384GB of data, 489,623 Files, and 53,577 Folders. The script finished in a little over 9.4 seconds, around 8 seconds when I added in a Cemu.exe for it to find. I feel the option do to so is helpful in situations like mine (where the processer is really powerful), but it may be detrimental if the User/~ folder is massive or the processer is slow. We should probably leave it in, but to prevent people from just closing the application we might consider using threading to allow user input (and thus allowing them to abort the scanning process).

**Comment by L1Z3** [comment]
Yes good plan!

**Review by L1Z3 — APPROVED** [review]

**Pull request merged**
